#!/usr/bin/env bash
# GraphVisual Installer — downloads the latest fat JAR and creates a launcher.
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/sauravbhattacharya001/GraphVisual/master/install.sh | bash
#   # or with a specific version:
#   curl -fsSL ... | bash -s -- --version v2.62.0

set -euo pipefail

REPO="sauravbhattacharya001/GraphVisual"
INSTALL_DIR="${GRAPHVISUAL_HOME:-$HOME/.graphvisual}"
BIN_DIR="${GRAPHVISUAL_BIN:-$HOME/.local/bin}"

# ---------- arg parsing ----------
VERSION=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --version|-v) VERSION="$2"; shift 2 ;;
    --dir|-d)     INSTALL_DIR="$2"; shift 2 ;;
    --help|-h)
      echo "Usage: install.sh [--version TAG] [--dir INSTALL_DIR]"
      echo "  --version TAG   Install a specific release (e.g. v2.62.0)"
      echo "  --dir DIR       Install directory (default: ~/.graphvisual)"
      exit 0 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# ---------- helpers ----------
info()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
ok()    { printf '\033[1;32m✔\033[0m   %s\n' "$*"; }
fail()  { printf '\033[1;31m✘\033[0m   %s\n' "$*" >&2; exit 1; }

command -v java >/dev/null 2>&1 || fail "Java is required but not found. Install JDK 11+ first."

JAVA_VER=$(java -version 2>&1 | head -1 | sed -E 's/.*"([0-9]+).*/\1/')
if [[ "$JAVA_VER" -lt 11 ]] 2>/dev/null; then
  fail "Java 11+ required (found Java $JAVA_VER)"
fi

# ---------- resolve version ----------
if [[ -z "$VERSION" ]]; then
  info "Fetching latest release..."
  if command -v gh >/dev/null 2>&1; then
    VERSION=$(gh release view --repo "$REPO" --json tagName -q .tagName 2>/dev/null || true)
  fi
  if [[ -z "$VERSION" ]]; then
    VERSION=$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" | grep '"tag_name"' | head -1 | sed -E 's/.*"([^"]+)".*/\1/')
  fi
fi
[[ -z "$VERSION" ]] && fail "Could not determine latest version."
info "Installing GraphVisual $VERSION"

# ---------- download ----------
mkdir -p "$INSTALL_DIR" "$BIN_DIR"

JAR_NAME="graphvisual-${VERSION#v}-all.jar"
JAR_URL="https://github.com/$REPO/releases/download/$VERSION/$JAR_NAME"

info "Downloading fat JAR..."
if command -v gh >/dev/null 2>&1; then
  gh release download "$VERSION" --repo "$REPO" --pattern "*-all.jar" --dir "$INSTALL_DIR" --clobber 2>/dev/null \
    || curl -fSL "$JAR_URL" -o "$INSTALL_DIR/$JAR_NAME"
else
  HTTP_CODE=$(curl -fSL -w "%{http_code}" "$JAR_URL" -o "$INSTALL_DIR/$JAR_NAME")
  if [[ "$HTTP_CODE" != "200" ]]; then
    # try alternate naming convention
    JAR_NAME="graphvisual-${VERSION#v}.jar"
    JAR_URL="https://github.com/$REPO/releases/download/$VERSION/$JAR_NAME"
    curl -fSL "$JAR_URL" -o "$INSTALL_DIR/$JAR_NAME" || fail "Download failed (HTTP $HTTP_CODE). Check the release assets."
  fi
fi

# find the actual downloaded JAR (gh may rename it)
ACTUAL_JAR=$(ls -t "$INSTALL_DIR"/*-all.jar 2>/dev/null | head -1)
[[ -z "$ACTUAL_JAR" ]] && ACTUAL_JAR="$INSTALL_DIR/$JAR_NAME"
[[ -f "$ACTUAL_JAR" ]] || fail "JAR not found after download."

ok "Downloaded $(basename "$ACTUAL_JAR")"

# store version for update checks
echo "$VERSION" > "$INSTALL_DIR/.version"

# ---------- create launcher ----------
LAUNCHER="$BIN_DIR/graphvisual"
cat > "$LAUNCHER" << 'LAUNCHER_EOF'
#!/usr/bin/env bash
# GraphVisual launcher — auto-generated by install.sh
set -euo pipefail

INSTALL_DIR="${GRAPHVISUAL_HOME:-$HOME/.graphvisual}"
JAR=$(ls -t "$INSTALL_DIR"/*-all.jar 2>/dev/null | head -1)

if [[ -z "$JAR" || ! -f "$JAR" ]]; then
  echo "GraphVisual JAR not found in $INSTALL_DIR" >&2
  echo "Run the installer again: https://github.com/sauravbhattacharya001/GraphVisual#quick-install" >&2
  exit 1
fi

# Check for updates (non-blocking, at most once per day)
UPDATE_CHECK="$INSTALL_DIR/.last-update-check"
NOW=$(date +%s)
if [[ ! -f "$UPDATE_CHECK" ]] || (( NOW - $(cat "$UPDATE_CHECK" 2>/dev/null || echo 0) > 86400 )); then
  (
    CURRENT=$(cat "$INSTALL_DIR/.version" 2>/dev/null || echo "unknown")
    LATEST=$(curl -fsSL --max-time 3 "https://api.github.com/repos/sauravbhattacharya001/GraphVisual/releases/latest" 2>/dev/null | grep '"tag_name"' | head -1 | sed -E 's/.*"([^"]+)".*/\1/' || true)
    if [[ -n "$LATEST" && "$LATEST" != "$CURRENT" ]]; then
      echo "ℹ️  GraphVisual $LATEST is available (current: $CURRENT). Run the installer to update." >&2
    fi
    echo "$NOW" > "$UPDATE_CHECK"
  ) &
fi

exec java -Djava.awt.headless="${GRAPHVISUAL_HEADLESS:-false}" "$@" -jar "$JAR"
LAUNCHER_EOF
chmod +x "$LAUNCHER"
ok "Launcher created at $LAUNCHER"

# ---------- verify PATH ----------
if ! echo "$PATH" | tr ':' '\n' | grep -qx "$BIN_DIR"; then
  info "Add $BIN_DIR to your PATH:"
  echo "  export PATH=\"$BIN_DIR:\$PATH\"  # add to ~/.bashrc or ~/.zshrc"
fi

# ---------- verify ----------
info "Verifying installation..."
java -Djava.awt.headless=true -jar "$ACTUAL_JAR" --help 2>&1 | head -5 || true
ok "GraphVisual $VERSION installed successfully!"
echo ""
echo "  Run:     graphvisual"
echo "  Docker:  docker run --rm ghcr.io/$REPO:latest"
echo "  Update:  re-run this installer"
echo ""
