name: Feature Request
description: Suggest a new feature or improvement for GraphVisual
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make GraphVisual better? We'd love to hear it.

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area does this feature relate to?
      options:
        - New Graph Algorithm
        - Visualization / UI
        - Data Pipeline / Database
        - Meeting Extraction / NLP
        - Performance
        - Developer Experience (build, CI, docs)
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any mockups, references, or examples that illustrate the idea.
